=head1 NAME

sessiond - standalone X session manager

=head1 SYNOPSIS

B<sessiond> [OPTIONS]

=head1 DESCRIPTION

sessiond is a standalone X session manager that reports the idle status of a
session to B<systemd-logind>(8) and handles its lock, unlock, sleep, and
shutdown signals. sessiond also provides hooks triggered by inactivity or a
signal, automatic backlight dimming on idle, and optional management of DPMS
settings.

=head1 OPTIONS

=over

=item B<-h>, B<--help>

Show help options.

=item B<-c>, B<--config>=I<CONFIG>

Path to config file. See B<sessiond.conf>(5) for configuration options.

=item B<-i>, B<--idle-sec>=I<SEC>

Seconds the session must be inactive before considered idle.

=item B<-v>, B<--version>

Show version.

=back

=head1 DBUS SERVICE

sessiond provides a DBus service on the session bus at the well-known name
I<org.sessiond.session1>.
The B<org.sessiond.session1.Session> interface exposes the following methods,
properties, and signals:

=head2 Methods

=over

=item B<Lock>

Lock the session. Returns an error if the session is already locked.

=item B<Unlock>

Unlock the session.

=back

=head2 Properties

=over

=item B<LockedHint>

The locked state of the session.

=item B<IdleHint>

The idle state of the session.

=item B<IdleSinceHint>

The timestamp of the last change to B<IdleHint>.

=item B<IdleSinceHintMonotonic>

The timestamp of the last change to B<IdleHint> in monotonic time.

=back

=head2 Signals

=over

=item B<Lock>

Emitted when the session is locked. B<LockedHint> will be true.

=item B<Unlock>

Emitted when the session is unlocked. B<LockedHint> will be false.

=item B<Idle>

Emitted when the session becomes idle. B<IdleHint> will be true.

=item B<Active>

Emitted when activity resumes in an inactive session.
B<IdleHint> will be false.

=item B<Inactive> B<seconds>

Emitted when the session becomes inactive, with the B<seconds> argument being
the number of seconds since activity. Its value will be equal to either the
I<IdleSec> or I<DimSec> configuration option (see B<sessiond.conf>(5)), or the
I<InactiveSec> option of a hook with an B<Inactive> trigger
(see B<sessiond-hooks>(5)).

=item B<PrepareForSleep> B<state>

Emitted before and after system sleep, with the B<state> argument being true
and false respectively.

=item B<PrepareForShutdown> B<state>

Emitted before and after system shutdown, with the B<state> argument being true
and false respectively.

=back

=over

=item For complete introspection data, use B<gdbus>(1):

B<gdbus> introspect --session --dest I<org.sessiond.session1> --object-path
I</org/sessiond/session1>

=back

=head1 DEBUGGING

Running sessiond with the environment variable I<G_MESSAGES_DEBUG> set to "all"
will print debug messages.

=head1 AUTHOR

James Reed E<lt>jcrd@tuta.ioE<gt>

=head1 REPORTING BUGS

Bugs and issues can be reported here: L<https://github.com/jcrd/sessiond/issues>

=head1 COPYRIGHT

Copyright 2018 James Reed. sessiond is licensed under the
GNU General Public License v3.0 or later.

=head1 SEE ALSO

B<sessiond.conf>(5), B<sessiond-hooks>(5), B<systemd-logind>(8), B<gdbus>(1)
