=head1 NAME

sessiond-hooks - sessiond hook file format

=head1 SYNOPSIS

=over

=item [Hook]

=item Trigger=Lock|Idle|Sleep|Shutdown|Inactive

=item InactiveSec=E<lt>secondsE<gt> (Inactive only)

=item ExecStart=E<lt>commandE<gt>

=item ExecStop=E<lt>commandE<gt> (Lock|Idle|Inactive only)

=back

=head1 DESCRIPTION

sessiond provides the ability to define hooks that are triggered by events.
The "Inactive" event is unique to hooks. It allows commands to be run after a
period of inactivity. It is more general than the "Idle" event, which occurs
after I<IdleSec> (see B<sessiond.conf>(5)) seconds of inactivity.

Hook files with the ".hook" suffix are read from
I<XDG_CONFIG_HOME>/sessiond/hooks.d or I<HOME>/.config/sessiond/hooks.d.

=head1 OPTIONS

=over

=item I<Trigger=>

Event type that will trigger the hook. Values are "Lock", "Idle", "Sleep",
"Shutdown", "Inactive".

=item I<InactiveSec=>

Seconds of inactivity after which the hook is triggered.

=item I<ExecStart=>

Command to execute when the hook is triggered.

=item I<ExecStop=>

Command to execute when the trigger event ends. For "Lock", this is when the
screen is unlocked. For "Idle" and "Inactive", this is when activity resumes.

=back

=head1 SEE ALSO

B<sessiond>(1), B<sessiond.conf>(5)
