#!/bin/sh

# sessiond - standalone X session manager
# Copyright (C) 2018 James Reed
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.

set -eu

readonly target=sessiond-session.target

isActive() {
    systemctl --user is-active "$1"
}

consistsOf() {
    systemctl --user show -p ConsistsOf --value "$1"
}

status() {
    active="$(isActive $target)"
    r=$?

    echo "$target: $active"

    if [ $r -eq 0 ]; then
        units="$(consistsOf graphical-session.target)"
        if [ -n "$units" ]; then
            i=0
            pad=${#target}
            for unit in $units; do
                i=$((i + 1))
                [ ${#unit} -gt $pad ] && pad=${#unit}
            done
            for unit in $units; do
                i=$((i - 1))
                [ $i -eq 0 ] && s='└' || s='├'
                printf "$s─%-${pad}s%s\n" "$unit:" "$(isActive "$unit")"
            done
        fi
    fi

    exit $r
}

[ $# -eq 0 ] && status

case "$1" in
    start)
        if systemctl --user -q is-active $target; then
            echo 'a session is already active' >&2
            exit 1
        fi
        systemctl --user import-environment
        exec systemctl --user --wait start $target
        ;;
    stop)
        systemctl --user stop $target
        ;;
    status)
        status
        ;;
    *)
        echo 'usage: sessiond-session [start|stop|status]' >&2
        exit 2
esac
